export type RegionKey = 'north' | 'west' | 'east' | 'central' | 'south' | 'latin';
export type LyricTemplate = 'chant' | 'verse-hook' | 'call-response' | 'cyclical' | 'narrative' | 'rapid-fire';

export interface Genre {
  key: string;
  name: string;
  region: RegionKey;
  emoji: string;
  tagline: string;
  bpm: [number, number];
  defaultLanguage: string;
  styleTags: string[];
  referenceArtists: string[];
  culturalDNA: string;
  hitFormula: string;
  lyricTemplate: LyricTemplate;
}

export interface Region {
  key: RegionKey;
  label: string;
  emoji: string;
}

export const REGIONS: Region[] = [
  { key: 'north',   label: 'N. Africa',   emoji: '🇲🇦' },
  { key: 'west',    label: 'W. Africa',   emoji: '🇳🇬' },
  { key: 'east',    label: 'E. Africa',   emoji: '🇹🇿' },
  { key: 'central', label: 'Central',     emoji: '🇨🇩' },
  { key: 'south',   label: 'S. Africa',   emoji: '🇿🇦' },
  { key: 'latin',   label: 'Afro-Latin',  emoji: '🌎' },
];

export const GENRES: Genre[] = [

  // ── NORTH AFRICA ─────────────────────────────────────────────────────
  {
    key: 'gnawa',
    name: 'Gnawa',
    region: 'north',
    emoji: '🇲🇦',
    tagline: 'Moroccan ritual trance',
    bpm: [90, 115],
    defaultLanguage: 'Darija Arabic + Bambara ceremonial phrases',
    styleTags: ['gnawa', 'moroccan spiritual', 'guembri bass', 'krakeb iron castanets', 'trance', 'hypnotic ritual', 'sufi blues', 'repetitive groove'],
    referenceArtists: ['Innov Gnawa', "Bab L'Bluz", 'Maalem Mahmoud Guinia'],
    culturalDNA: `Gnawa is Moroccan healing and trance music descended from enslaved Sub-Saharan Africans. The guembri (3-string bass lute) delivers a warm woody plucked groove — hypnotic and syncopated. Iron castanets (krakeb) play interlocking metallic patterns. Vocals are communal call-and-response chants, not solo performance. Structure is cyclical: repetition IS the spiritual technology that induces trance. Ceremonies are organized by "colors" (mluk) — black, blue, red, green — each evoking a different spirit. Modern fusion works by layering Afro House, jazz, or blues on top of the guembri+krakeb foundation.`,
    hitFormula: 'REPETITION IS TRANSCENDENCE. The same phrase 20 times takes you somewhere new. The guembri bass must lock in immediately. Global crossover happens when this hypnotic bottom end meets electronic production — keep it deep, patient, ancient.',
    lyricTemplate: 'cyclical',
  },
  {
    key: 'rai',
    name: 'Raï',
    region: 'north',
    emoji: '🇩🇿',
    tagline: 'Algerian rebel soul',
    bpm: [110, 135],
    defaultLanguage: 'Darija Arabic (Algerian dialect) with French words scattered in',
    styleTags: ['rai', 'algerian pop', 'north african', 'derbouka percussion', 'gasba flute', 'synthesizer lead', 'electric guitar', 'emotional arabic vocals'],
    referenceArtists: ['Khaled', 'Cheb Mami', 'Cheb Bilal', 'Cheba Fadela'],
    culturalDNA: `Raï emerged from working-class Oran, Algeria — forbidden street music dealing openly with love, alcohol, and social taboo. Electrified in the 1980s by adding synthesizers, drum machines, and electric guitar to traditional derbouka goblet drum and gasba shepherd's flute. Vocal delivery is raw and emotionally charged — a cross between a cry and a celebration. Singers ornament melodies with Arabic maqam inflections but sing in colloquial Darija. Modern Raï fuses with trap (the "Way-Way" sub-genre in Algeria). Key production: synthesizer lead doubling the vocal melody, driving derbouka pattern, syncopated electric guitar rhythm.`,
    hitFormula: 'VOICE + PAIN = LIBERATION. The singer sounds broken and free simultaneously. The hook must be melodically simple but emotionally devastating. Add a recognizable synth or brass riff as a recurring signature. Call-and-response between lead and backing chorus.',
    lyricTemplate: 'call-response',
  },
  {
    key: 'mahraganat',
    name: 'Mahraganat',
    region: 'north',
    emoji: '🇪🇬',
    tagline: 'Cairo street chaos',
    bpm: [130, 155],
    defaultLanguage: 'Egyptian Arabic (Masri) — street dialect, very colloquial',
    styleTags: ['mahraganat', 'electro shaabi', 'egyptian street', 'darbuka percussion', 'mizmar synth lead', 'cairo underground', 'autotune vocals', 'arabic trap'],
    referenceArtists: ['DJ Figo', 'DJ Souissy', 'Sadat & Fifty', 'Wegz'],
    culturalDNA: `Mahraganat emerged from Cairo's working-class neighborhoods in 2006–2007 as DIY wedding DJ music made in FL Studio. It combines traditional Egyptian sha'bi folk music with EDM, trap, and grime. The signature sound is a sawtooth synthesizer mimicking the mizmar (Egyptian oboe) — aggressive and nasal. Darbuka drives the rhythm. Vocals are fast-rapped in Egyptian street slang (Masri), heavily auto-tuned, shouted not sung. Lyrics are social commentary and humor. Zero production polish is a feature not a bug — it represents the streets speaking for themselves.`,
    hitFormula: 'SPEED + CHAOS + HUMOR = CATHARSIS. Fast-talking street comedy with sharp social observation. The two-word drop chant repeated by a crowd is the hit moment. The mizmar-style synth lead must be unmistakably Egyptian. Energy never drops.',
    lyricTemplate: 'rapid-fire',
  },
  {
    key: 'nubian',
    name: 'Nubian',
    region: 'north',
    emoji: '🇸🇩',
    tagline: 'Ancient Nile soul',
    bpm: [90, 115],
    defaultLanguage: 'Nubian language or Arabic with Nubian phrases',
    styleTags: ['nubian music', 'nubian folk', 'pentatonic melody', 'simsimiyya lyre', 'nile valley', 'warm oud', 'frame drum', 'ancient african'],
    referenceArtists: ['Ali Hassan Kuban', 'Mohamed Mounir', 'Hamza El Din'],
    culturalDNA: `Nubian music comes from the ancient civilization along the Nile in southern Egypt and northern Sudan. The Nubian pentatonic scale is uniquely warm — unlike anything else in North Africa or the Middle East. The simsimiyya (lyre) creates a shimmering ancient texture. Rhythms are softer and more circular than Arab music. After the Aswan High Dam flooded their ancestral lands in the 1960s, Nubian music became an act of cultural preservation and longing. That emotional weight of exile and memory infuses everything. Mohamed Mounir fused it successfully with jazz and pop.`,
    hitFormula: 'MEMORY + LONGING + THE RIVER. Reference the Nile, the old village, the displacement. The pentatonic melody should be hauntingly simple — anyone can hum it after one listen. Acoustic warmth signals authenticity. Live instruments over electronic where possible.',
    lyricTemplate: 'narrative',
  },
  {
    key: 'chaabi',
    name: 'Chaabi',
    region: 'north',
    emoji: '🇲🇦',
    tagline: 'Moroccan street poetry',
    bpm: [90, 120],
    defaultLanguage: 'Darija Arabic (Moroccan dialect)',
    styleTags: ['chaabi', 'moroccan folk', 'north african', 'oud melody', 'violin', 'bendir frame drum', 'andalusian influence', 'poetic arabic vocals'],
    referenceArtists: ['Nass El Ghiwane', 'Jil Jilala', 'Maalem Mahmoud Guinia'],
    culturalDNA: `Moroccan Chaabi ("people's music") is urban street poetry rooted in Andalusian and Arabic classical traditions. Features oud, violin, frame drums (bendir), and powerful vocal improvisation. Lyrics are in Darija — deeply poetic, dealing with love, social commentary, and mysticism. Electro-Chaabi adds digital beats and synth basslines under the acoustic arrangement. Nass El Ghiwane combined Sufi mysticism with political poetry in the 1970s and redefined what Chaabi could say.`,
    hitFormula: 'POETRY FIRST. The words must be beautiful in Darija before the music supports them. Oud melody is the emotional spine. Violin provides depth. The rhythm section should be acoustic but precise.',
    lyricTemplate: 'call-response',
  },

  // ── WEST AFRICA ──────────────────────────────────────────────────────
  {
    key: 'afrobeats',
    name: 'Afrobeats',
    region: 'west',
    emoji: '🇳🇬',
    tagline: 'Nigerian global heat',
    bpm: [100, 112],
    defaultLanguage: 'English + Yoruba or Pidgin mix',
    styleTags: ['afrobeats', 'nigerian pop', 'afropop', 'syncopated percussion', 'offbeat shaker groove', '808 sub bass', 'highlife guitar stabs', 'melodic rap-sing'],
    referenceArtists: ['Burna Boy', 'Wizkid', 'Rema', 'Davido', 'Ayra Starr', 'Tems', 'Asake'],
    culturalDNA: `Modern Afrobeats emerged from Lagos in the early 2000s, fusing Yoruba highlife, Caribbean dancehall, and American hip-hop with West African polyrhythm. Rhythm foundation: syncopated kick (doesn't always land on beat 1), off-beat shaker/maracas at 8th or 16th notes (the motor), clap/snare slightly behind beat 3 (the lazy swagger), rubbery 808 sub-bass moving melodically, bright guitar or synth stabs from highlife tradition. Vocal style blurs rapping and singing. Lyrics mix English with Yoruba/Pidgin: verse in local language, chorus in English with 1–2 Yoruba hook words. Production in 2025 is sparse but heavy — few elements, controlled low end for mobile speakers.`,
    hitFormula: 'HOOK > EVERYTHING. The hook must work without music — singable, 3–6 syllables, emotional. Arrives within 40 seconds. One specific Nigerian imagery reference per verse (Lagos at night, the hustle, Lekki). Track should feel like summer everywhere on earth.',
    lyricTemplate: 'verse-hook',
  },
  {
    key: 'highlife',
    name: 'Highlife',
    region: 'west',
    emoji: '🇬🇭',
    tagline: 'Ghanaian brass & guitar',
    bpm: [100, 130],
    defaultLanguage: 'English + Twi or Ga phrases',
    styleTags: ['highlife', 'ghana highlife', 'afro highlife', 'brass horns', 'rapid guitar picking', 'trumpet', 'saxophone', 'joyful west african'],
    referenceArtists: ['E.T. Mensah', 'Pat Thomas', 'Amakye Dede', 'KiDi'],
    culturalDNA: `Highlife was born in Ghana in the late 19th century, fusing traditional Akan music with Western brass band and Caribbean influences. Defining elements: bright melodic guitar picking (rapid single-note runs — the genre signature), brass section (trumpet, trombone, saxophone), and joyful communal vocals. The guitar work is the heart — intricate, celebratory, impossible to separate from the genre's identity. Modern highlife blends Afrobeats percussion patterns underneath traditional guitar and horn vocabulary. KiDi and Kuami Eugene bring it to global streaming. Highlife is fundamentally joyful community music — made when being African in a suit was radical elegance.`,
    hitFormula: 'THE GUITAR MELODY IS THE SONG. If the guitar riff is not memorable, nothing else matters. Brass adds celebration and lift. Joy is the primary emotion — even sad highlife sounds warm and communal. The groove should make you want to dance without being aggressive.',
    lyricTemplate: 'verse-hook',
  },
  {
    key: 'afropop',
    name: 'Afropop',
    region: 'west',
    emoji: '🌍',
    tagline: 'Pan-African streaming hit',
    bpm: [100, 115],
    defaultLanguage: 'English + local language blend',
    styleTags: ['afropop', 'african pop', 'hook-driven', 'synth bass', 'melodic', 'radio ready', 'pan-african', 'streaming optimized'],
    referenceArtists: ['Tyla', 'Ckay', 'Fireboy DML', 'Omah Lay', 'Simi'],
    culturalDNA: `Afropop is the crossover umbrella — African music made with global streaming in mind. It takes the emotional directness of Afrobeats, Highlife, and Amapiano and packages it with Western pop structure for maximum accessibility. Production is clean and polished. Hooks are simple and universal. African identity comes through in rhythm (syncopated, polyrhythmic at heart even when polished) and emotional delivery. Tyla's "Water" is the definitive template: minimal, infectious, globally understood. Afropop is where African music talks to the world on pop's terms while keeping its soul.`,
    hitFormula: 'UNIVERSAL EMOTION + AFRICAN RHYTHM = GLOBAL HIT. One-word title that is also a feeling. Chorus hook: 4 words or less. One distinctive African percussion element in otherwise clean production. 3 minutes total, hook within 30 seconds. Think streaming-first.',
    lyricTemplate: 'verse-hook',
  },
  {
    key: 'juju',
    name: 'Jùjú',
    region: 'west',
    emoji: '🇳🇬',
    tagline: 'Yoruba talking drum praise',
    bpm: [80, 110],
    defaultLanguage: 'Yoruba',
    styleTags: ['juju', 'yoruba music', 'talking drum gangan', 'electric guitar', 'steel pedal guitar', 'west african traditional', 'call and response', 'praise music'],
    referenceArtists: ['King Sunny Ade', 'Ebenezer Obey', 'Sir Shina Peters'],
    culturalDNA: `Juju is Yoruba music from Nigeria, with the talking drum (gangan) as its beating heart — it literally mimics the tonal Yoruba language, creating a conversation between drum and vocalist unique in world music. Electric guitar (lead and rhythm), steel pedal guitar, vibraphone, dense percussion ensemble (sakara, sekere, agogo), and call-and-response vocals create rich layered texture. Traditional Juju tracks run 15–20 minutes — long slow-building grooves. Music channels Yoruba spiritual energy and praises chiefs and life events. King Sunny Ade brought it to global attention in the 1980s.`,
    hitFormula: 'THE TALKING DRUM LEADS. The gangan conversation with the vocalist is the core of the track. Long builds are tradition — do not rush the drop. Layer percussion gradually. Yoruba proverbs and praise poetry are the lyrical vocabulary.',
    lyricTemplate: 'call-response',
  },
  {
    key: 'coupe_decale',
    name: 'Coupé-Décalé',
    region: 'west',
    emoji: '🇨🇮',
    tagline: 'Ivorian club swagger',
    bpm: [110, 140],
    defaultLanguage: 'Nouchi (Ivorian street French) + French',
    styleTags: ['coupe decale', 'ivorian music', 'west african club', 'percussive electronic beats', 'congolese influence', 'atalaku hype vocal', 'african dance music'],
    referenceArtists: ['Douk Saga', 'DJ Arafat', 'Josey'],
    culturalDNA: `Coupé-Décalé ("cut and run" in Nouchi slang) emerged from the Ivorian diaspora in Paris around 2002, then swept back to Abidjan. Takes Congolese Ndombolo rhythm programming and adds Ivorian swagger — computer-programmed beats with tight percussive African patterns. The atalaku (hype man) vocal style is a defining production element — a running commentary that motivates specific dance moves. DJ Arafat was the king: his productions had one purpose — make bodies move in choreographed ways. Each hit track defines its own dance. Fast, percussive, joyful, unapologetically club-focused.`,
    hitFormula: 'THE DANCE DEFINES THE SONG. The track needs a 15-second section so rhythmically irresistible it invents its own dance move. Atalaku hype voice builds energy. Percussive Congolese-influenced groove. Fast and relentless — never let the energy drop.',
    lyricTemplate: 'rapid-fire',
  },
  {
    key: 'afro_drill',
    name: 'Afro Drill',
    region: 'west',
    emoji: '🏙️',
    tagline: 'Lagos street energy, mixed voices',
    bpm: [118, 128],
    defaultLanguage: 'English + Yoruba/Pidgin street mix',
    styleTags: ['afro drill', 'urban afrobeats', 'street afro', '808 sub bass', 'punchy kick', 'dark piano', 'male rap vocal', 'female melodic hook', 'remastered', 'gritty', 'burna boy style'],
    referenceArtists: ['Burna Boy', 'Rema', 'Victony', 'Shallipopi', 'Central Cee × Afrobeats'],
    culturalDNA: `Afro Drill is the Lagos/Joburg street sound — urban Afrobeats with UK Drill's dark energy and storytelling directness. 808 sub bass pitch-slides under a punchy kick. Hi-hats triplet or 16th-note with open hats. Dark minimal piano hook (3–5 notes). MIXED VOICES: male deep rap/spoken word in verses (street storytelling, specific Lagos imagery — danfo buses, neon signs, designer shoes, mama's prayers) with [Male] label; female soulful melodic hook in chorus (emotional contrast) with [Female] label. Duet moments in bridge with [Duet] label. Lyrics mix English with Yoruba and Pidgin naturally. -8 LUFS remastered production. Add performance tags: (male, deep), (rap), (female, soulful), (melodic hook), (breathy), (duet).`,
    hitFormula: 'MIXED VOICES = THE CONTRAST IS THE HIT. Male gritty verse → female melodic chorus = emotional push-pull that hooks everyone. The 808 must be felt in the chest. Specific street imagery per verse (a Lagos street name, danfo color, neon sign brand). Hook before 40 seconds. Production at -8 LUFS — louder than Afro House.',
    lyricTemplate: 'rapid-fire',
  },

  // ── EAST AFRICA ──────────────────────────────────────────────────────
  {
    key: 'bongo_flava',
    name: 'Bongo Flava',
    region: 'east',
    emoji: '🇹🇿',
    tagline: 'Swahili pop soul',
    bpm: [85, 110],
    defaultLanguage: 'Swahili (primary) + English in bridge/chorus',
    styleTags: ['bongo flava', 'tanzanian pop', 'swahili pop', 'afrobeats influenced', 'east african', 'bongopiano', 'melodic swahili vocals', 'romantic groove'],
    referenceArtists: ['Diamond Platnumz', 'Zuchu', 'Ali Kiba', 'Harmonize'],
    culturalDNA: `Bongo Flava is Tanzania's pop music — a fusion of American hip-hop, R&B, Afrobeats, and traditional Tanzanian music (Taarab, Dansi). Swahili is its soul: the language has a flowing melodic quality that lends itself beautifully to pop songwriting. Diamond Platnumz proved it travels globally by collaborating with Nigerian Afrobeats artists and creating Bongopiano (Amapiano + Bongo Flava). Taarab harmonic influence gives chord progressions a distinctive Arabic-tinged warmth. The emotional core is romantic — love, longing, loyalty. Location references matter: Dar es Salaam, Tanzania, East Africa as identity markers.`,
    hitFormula: 'SWAHILI HOOK FIRST. If the Swahili phrase is melodically beautiful and emotionally resonant, the track travels. Nigerian Afrobeats rhythm but with Tanzanian harmonic warmth. Reference a specific East African place. Romance is the primary theme.',
    lyricTemplate: 'narrative',
  },
  {
    key: 'benga',
    name: 'Benga',
    region: 'east',
    emoji: '🇰🇪',
    tagline: 'Kenyan guitar cascade',
    bpm: [100, 130],
    defaultLanguage: 'Luo, Kikuyu, or Swahili',
    styleTags: ['benga', 'kenyan music', 'luo music', 'east african guitar', 'bright cascading guitar', 'polyrhythmic drums', 'kenyan folk', 'joyful communal'],
    referenceArtists: ['D.O. Misiani', 'Victoria Kings', 'Ayub Ogada'],
    culturalDNA: `Benga is Kenya's guitar tradition, born from the Luo community around Lake Victoria in the 1950s–60s. Its defining sound: rapid bright cascading single-note guitar runs influenced by country and western technique but completely African in feel. The guitar dances around the rhythm section. Polyrhythmic drum patterns create complex interplay underneath. Vocals in Luo, Kikuyu, or Swahili are storytelling about community life. Benga is fundamentally uplifting and communal — made to be danced to at social gatherings. Its influence runs through all East African guitar music.`,
    hitFormula: 'THE GUITAR CASCADE IS EVERYTHING. If the lead guitar melody is bright, fast, and joyful, it works. Build from polyrhythmic drums upward. Vocals should feel like storytelling and community, not ego.',
    lyricTemplate: 'narrative',
  },
  {
    key: 'taarab',
    name: 'Taarab',
    region: 'east',
    emoji: '🇹🇿',
    tagline: 'Zanzibar string elegance',
    bpm: [70, 95],
    defaultLanguage: 'Kiswahili — poetic, literary register',
    styleTags: ['taarab', 'swahili classical', 'zanzibar music', 'violin strings', 'arabic influenced harmony', 'romantic poetry', 'kiswahili', 'elegant orchestral'],
    referenceArtists: ['Siti binti Saad', 'Culture Musical Club', 'Zuchu (modern fusion)'],
    culturalDNA: `Taarab is the sophisticated court music of Zanzibar — Kiswahili poetry sung over Arabic-influenced string orchestration (violin, cello, oud, qanun zither). It blends East African, Arabic, Indian, and European musical traditions that met on Zanzibar's trade routes. The poetry is highly literary — allusive, layered with meaning, often about romantic politics and longing. Modern taarab (Zuchu's productions) keeps the harmonic richness and string color while adding Bongo Flava/Afrobeats rhythms underneath.`,
    hitFormula: 'POETRY + STRINGS = TIMELESS. Lyrical craft must be impeccable — taarab listeners analyze every word. The violin melody is the emotional spine. Elegance and sophistication over energy. Modern productions add rhythmic beds while preserving the string warmth.',
    lyricTemplate: 'narrative',
  },

  // ── CENTRAL AFRICA ───────────────────────────────────────────────────
  {
    key: 'soukous',
    name: 'Soukous',
    region: 'central',
    emoji: '🇨🇩',
    tagline: 'Congolese guitar paradise',
    bpm: [100, 135],
    defaultLanguage: 'Lingala + French phrases',
    styleTags: ['soukous', 'congolese rumba', 'lingala', 'lead guitar improvisation', 'seben dance section', 'flowing rumba groove', 'central african', 'joyful dance'],
    referenceArtists: ['Papa Wemba', 'Koffi Olomidé', 'Franco', 'Tabu Ley Rochereau'],
    culturalDNA: `Soukous is evolved Congolese Rumba that became pan-African. The lead guitar is the star: cascading melodic improvisation in the "seben" (dance/guitar section) that accelerates through the track. Traditional Soukous used large ensembles of 20+ musicians. The groove is flowing and swaying — bass and rhythm create a current that carries you. Vocals in Lingala and French. The seben section — extended guitar instrumental breakdown in the second half — is where the magic lives. Papa Wemba and Franco defined the form. Soukous influenced music across all of Africa.`,
    hitFormula: 'THE GUITAR LEAD IN THE SEBEN IS THE HIT. Everything before the seben is buildup. The guitar improvisation that accelerates in the second half is what people remember. Make the groove irresistibly warm. Lingala words should flow like water.',
    lyricTemplate: 'verse-hook',
  },
  {
    key: 'ndombolo',
    name: 'Ndombolo',
    region: 'central',
    emoji: '🇨🇩',
    tagline: 'Congolese frenetic dance',
    bpm: [140, 175],
    defaultLanguage: 'Lingala',
    styleTags: ['ndombolo', 'congolese dance', 'fast tempo', 'synthesizer', 'congolese guitar texture', 'central african', 'frenetic energy', 'high-speed dance'],
    referenceArtists: ['Koffi Olomidé', 'Wenge Musica', 'Extra Musica'],
    culturalDNA: `Ndombolo evolved from Soukous in the 1990s — faster, more electronic, more intense. Where Soukous is warm and flowing, Ndombolo is frenetic and demanding. Faster syncopated rhythms, synthesizer production overlaid on Congolese guitar foundation. It's named after the hip-shaking dance it accompanies — the dance defines the music. Pure dancefloor energy: it demands physical response. Modern productions are more electronic while keeping the Congolese guitar texture and Lingala vocal character.`,
    hitFormula: 'THE DANCE IS THE PRODUCT. Maximum rhythm complexity at high speed. The Congolese guitar texture gives it DNA, the tempo gives it energy. Every 8 bars should feel like an escalation.',
    lyricTemplate: 'rapid-fire',
  },
  {
    key: 'makossa',
    name: 'Makossa',
    region: 'central',
    emoji: '🇨🇲',
    tagline: 'Cameroonian bounce & horns',
    bpm: [130, 165],
    defaultLanguage: 'French + Duala or Cameroon Pidgin English',
    styleTags: ['makossa', 'cameroon music', 'african dance', 'guitar', 'brass horns', 'saxophone', 'trumpet', 'springy bass groove', 'celebratory'],
    referenceArtists: ['Manu Dibango', 'Charlotte Mbango', 'Grace Decca'],
    culturalDNA: `Makossa is the national music of Cameroon. Manu Dibango's "Soul Makossa" (1972) was sampled by Michael Jackson and Rihanna — proof of its global DNA. The guitar interplay between lead and rhythm is central. The bass creates a springy bouncing groove. Horns (saxophone, trumpet) add celebration and color. Lyrics in French, Duala, or Pidgin English. The makossa bounce: a specific kick and bass pattern that creates an irresistible swaying physical response. Cameroonian pride and community celebration are the emotional core.`,
    hitFormula: 'THE MAKOSSA BOUNCE. The kick and bass pattern creates a specific physical response — a bouncing swaying motion that is unmistakable. Guitar interplay creates the texture. Add horns for lift. Reference Cameroon specifically — this music is proudly local.',
    lyricTemplate: 'verse-hook',
  },

  // ── SOUTHERN AFRICA ──────────────────────────────────────────────────
  {
    key: 'afro_house',
    name: 'Afro House',
    region: 'south',
    emoji: '🇿🇦',
    tagline: 'Deep SA hypnotic groove',
    bpm: [115, 122],
    defaultLanguage: 'English + Zulu or Xhosa phrases',
    styleTags: ['afro house', 'south african deep house', 'sine sub bass', 'sparse congas', 'kalimba motif', 'warm 9th pads', 'hypnotic', 'soulful'],
    referenceArtists: ['Black Coffee', 'Keinemusik', 'Caiiro', 'Themba', 'Enoo Napa'],
    culturalDNA: `Deep Afro House is South Africa's contribution to global dance music — minimal, hypnotic, warm. Black Coffee's approach defines the gold standard: less is more, every element earns its place, the groove is patient not aggressive. Warm kick with soft transient. Sine-wave sub bass sidechained to kick. Hi-hats on offbeats with velocity variation (human feel). Sparse congas or djembe — live feel, not quantized tight. Kalimba, kora, or thumb piano melodic motifs — simple 2–4 note hooks. Warm sustained pads with 7th and 9th chords. Vocal samples are short soulful phrases or chants — not full pop structure. Built for long DJ sets: 6–8 minute tracks with long intros and outros.`,
    hitFormula: 'GROOVE > MELODY. The rhythm IS the song. One vocal phrase, looped with variations. Patience — let the groove breathe for 32 bars before adding the next element. People close their eyes and sway. A crowd-connecting moment, not a crowd-pumping one.',
    lyricTemplate: 'chant',
  },
  {
    key: 'amapiano',
    name: 'Amapiano',
    region: 'south',
    emoji: '🇿🇦',
    tagline: 'Log drum piano fever',
    bpm: [108, 114],
    defaultLanguage: 'English + Zulu, Sotho, or Tswana phrases',
    styleTags: ['amapiano', 'south african pop', 'log drum bassline', 'jazzy piano stabs', 'rhodes keys', 'shaker loops', 'warm sub bass', 'johannesburg sound'],
    referenceArtists: ['Kabza De Small', 'DJ Maphorisa', 'Sun-El Musician', 'Focalistic'],
    culturalDNA: `Amapiano ("the pianos" in Zulu) emerged from Johannesburg's townships around 2012–2016. Signature elements: the log drum bassline (boomy organic bass — the heartbeat), jazzy piano keys/stabs (Rhodes-style, funky and off-beat), shaker loops, warm sub bass. BPM sits in a relaxed locked groove (108–114). Vocals range from deep house chants to full R&B-influenced singing. Amapiano has crossed over globally — Afropiano (Amapiano + Afrobeats) is one of the most successful African fusions of 2024–2025. Sophisticated jazzy harmonies over raw bass-heavy production.`,
    hitFormula: 'THE LOG DRUM BASS IS NON-NEGOTIABLE. Without it, it is not Amapiano. Piano stabs should be jazzy but groove-locked. The BPM pocket (108–114) is sacred. Vocals feel easy and relaxed over the groove.',
    lyricTemplate: 'chant',
  },
  {
    key: 'gqom',
    name: 'Gqom',
    region: 'south',
    emoji: '🇿🇦',
    tagline: 'Durban raw dark bass',
    bpm: [125, 135],
    defaultLanguage: 'Zulu + English',
    styleTags: ['gqom', 'south african', 'durban sound', 'dark percussive', 'heavy kick', 'deep distorted bass', 'raw electronic', 'south african underground'],
    referenceArtists: ['Babes Wodumo', 'DJ Lag', 'Okmalumkoolkat'],
    culturalDNA: `Gqom (Zulu for "drum") is Durban's underground club music — darker, rawer, and more minimal than Amapiano. Emerged around 2012 in Durban's township clubs. Heavy relentless kick. Deep distorted bassline. Aggressive hypnotic percussion. Where Amapiano is warm and jazzy, Gqom is cold and harsh — but magnetic. Vocals are sparse, often just one chanted phrase. First South African genre to gain significant European underground club attention. The rawness is the point.`,
    hitFormula: 'THE KICK IS A WEAPON. Heavy, dark, relentless. The bass should feel like the floor moving. Keep it minimal — empty space creates tension. One vocal phrase maximum. Club music for people who dance alone in crowds.',
    lyricTemplate: 'chant',
  },
  {
    key: 'kwaito',
    name: 'Kwaito',
    region: 'south',
    emoji: '🇿🇦',
    tagline: 'Township house swagger',
    bpm: [95, 110],
    defaultLanguage: 'Isicamtho (township slang) + Zulu/Sotho',
    styleTags: ['kwaito', 'south african', 'slowed house', 'township street', 'hip hop influenced', 'zulu vocals', 'johannesburg township', 'post-apartheid pride'],
    referenceArtists: ['Arthur Mafokate', 'TKZee', 'Boom Shaka', 'Mzekezeke'],
    culturalDNA: `Kwaito emerged post-apartheid in Johannesburg's townships in the early 1990s — South Africa's liberation music. Slowed-down house music with township street slang (Isicamtho) rapped over it. BPM 95–110 creates a lazy swaggering feel. Hip-hop and American R&B influenced the vocal style. It represented the new freedom and identity of young Black South Africans after apartheid — joyful, defiant, street-level proud. Lyrics mix Zulu, Sotho, Tswana, and English township slang. Kwaito is the ancestor of Amapiano.`,
    hitFormula: 'SWAGGER IS THE RHYTHM. Slowed house groove with township slang creates specific pride and joy. Vocal delivery is half-sung half-spoken — confidently casual. Reference Johannesburg, township life, freedom. This is post-apartheid joy.',
    lyricTemplate: 'verse-hook',
  },
  {
    key: 'tribal_house',
    name: 'Tribal House',
    region: 'south',
    emoji: '🥁',
    tagline: 'Ancient drums meet deep house',
    bpm: [120, 126],
    defaultLanguage: 'English + Zulu chant',
    styleTags: ['tribal house', 'afro house', 'djembe', 'talking drum', 'congas', 'ethnic percussion', 'spiritual chant', 'hypnotic', 'ancestral', 'organic', 'deep house foundation'],
    referenceArtists: ['Enoo Napa', 'Caiiro', 'Culoe De Song', 'Hyenah', 'Themba'],
    culturalDNA: `Tribal House fuses traditional African percussion vocabulary with deep house electronic production. Talking drum or djembe drives the groove with live feel — slightly off the grid, human. Congas, shakers, and handclaps layer complex polyrhythmic patterns that feel ancient. Electronic kick and bass ground it in house. Vocals are minimal — short spiritual chants, African language phrases, call-and-response fragments. The production should feel like a ceremony happening inside a club. Every percussion hit carries cultural meaning — it is not decoration.`,
    hitFormula: 'THE DRUM IS THE ANCESTOR SPEAKING. Multiple percussion layers create a shifting hypnotic tapestry. Vocals are calls to the ancestors, not pop hooks. Patient long builds. The drop reveals the full percussive ensemble together.',
    lyricTemplate: 'chant' as LyricTemplate,
  },
  {
    key: 'organic_house',
    name: 'Organic House',
    region: 'south',
    emoji: '🌿',
    tagline: 'Acoustic textures, deep groove',
    bpm: [120, 126],
    defaultLanguage: 'English + African chant phrases',
    styleTags: ['organic house', 'afro house', 'acoustic guitar', 'kalimba', 'flute', 'live strings', 'warm bass', 'breathy female vocal', 'minimal electronic', 'keinemusik style', 'deep house'],
    referenceArtists: ['Keinemusik', 'Black Coffee', 'Âme', 'ANDHIM', 'Sébastien Léger'],
    culturalDNA: `Organic House sits at the intersection of deep house and acoustic music — the warmth of live instruments inside electronic production. Acoustic guitar, flute, kalimba, hand drums, and live strings replace synthesizers. The production is minimal and breathing — lots of space. Female vocals are breathy and short, more texture than melody. Sub bass is warm and round, not distorted. The groove is patient and hypnotic. Organic House works globally because it sounds human in a world of digital perfection. Keinemusik aesthetic: effortlessly cool, warm enough to feel alive.`,
    hitFormula: 'SPACE IS AN INSTRUMENT. What you leave out defines the track. One acoustic element (guitar, flute, or kalimba) carries the melodic identity. Bass breathes under a soft kick. Vocals are felt not forced. Should sound perfect at sunset on a rooftop in Cape Town or Ibiza.',
    lyricTemplate: 'chant' as LyricTemplate,
  },
  {
    key: 'afropiano',
    name: 'Afropiano',
    region: 'south',
    emoji: '🎹',
    tagline: 'Amapiano meets Afrobeats heat',
    bpm: [110, 116],
    defaultLanguage: 'English + Zulu + Yoruba mix',
    styleTags: ['afropiano', 'amapiano', 'afrobeats', 'log drum bass', 'jazzy piano stabs', 'afrobeats percussion', 'pan-african fusion', 'melodic hook', 'warm', 'sun-el musician style'],
    referenceArtists: ['Sun-El Musician', 'Kabza De Small', 'Focalistic', 'Omah Lay', 'Ckay'],
    culturalDNA: `Afropiano is the most commercially successful Pan-African fusion of 2024–2025 — Amapiano's log drum bass and jazzy piano vocabulary meeting Afrobeats' melodic hooks and West African percussion energy. The log drum bass is mandatory. Piano stabs are jazzy (dominant 7ths, suspended chords) but groove-locked. Shaker loops and Afrobeats percussion sit on top of the Amapiano foundation. Vocal style borrows from Afrobeats: melodic and hook-driven. Lyrics mix Zulu or Sotho township slang with Yoruba and English — sonic representation of a Pan-African generation.`,
    hitFormula: 'LOG DRUM + AFROBEATS HOOK = PAN-AFRICAN HIT. Log drum bass is mandatory and must be felt. Piano stabs jazzy but danceable. Vocal hook as catchy as Afrobeats pop but in Amapiano\'s relaxed pocket. Mix both West and South African language references per verse.',
    lyricTemplate: 'verse-hook' as LyricTemplate,
  },

  // ── AFRO-LATIN ───────────────────────────────────────────────────────
  {
    key: 'kuduro',
    name: 'Kuduro',
    region: 'latin',
    emoji: '🇦🇴',
    tagline: 'Angolan electronic fury',
    bpm: [128, 145],
    defaultLanguage: 'Portuguese + Kimbundu phrases',
    styleTags: ['kuduro', 'angolan music', 'african electronic', 'fast bass', 'electronic beats', 'portuguese vocals', 'afro latin', 'maximum dance energy'],
    referenceArtists: ['Tony Amado', 'Buraka Som Sistema', 'Os Lambas', 'C4 Pedro'],
    culturalDNA: `Kuduro ("hard ass" in Portuguese slang) is Angola's explosive electronic music — fast, raw, unapologetically energetic. Born in Luanda in the early 1990s, combining electronic production with Angolan semba rhythms, Caribbean zouk, and aggressive electronic bass. Buraka Som Sistema took it to global clubs. Vocals in Portuguese and Kimbundu, shouted and rhythmic. Productions are fast and relentless. The dance style is as important as the music — exaggerated high-energy body movements. Kuduro proved African electronic music had global club potential before Afrobeats and Amapiano did.`,
    hitFormula: 'MAXIMUM ENERGY, NO APOLOGIES. The tempo is aggressive. The bass hits hard and fast. Vocals are shouted not sung. Reference Angola and Luanda specifically. The production should feel like a street party that refuses to stop.',
    lyricTemplate: 'rapid-fire',
  },
  {
    key: 'kizomba',
    name: 'Kizomba',
    region: 'latin',
    emoji: '🇦🇴',
    tagline: 'Angolan sensual slow burn',
    bpm: [80, 95],
    defaultLanguage: 'Portuguese + Kimbundu',
    styleTags: ['kizomba', 'angolan music', 'semba influenced', 'slow sensual groove', 'caribbean zouk', 'warm synthesizer pads', 'romantic portuguese vocals', 'intimate'],
    referenceArtists: ['Nelson Freitas', 'Anselmo Ralph', 'Yola Semedo', 'Sara Tavares'],
    culturalDNA: `Kizomba ("party" in Kimbundu) is the slow sensual cousin of Kuduro — both Angolan, opposite in energy. Evolved from Angolan semba through Caribbean zouk influence. Slow intimate groove built for close partner dancing. Warm present bass. Synthesizer pads create a cushion of sound. Vocals in Portuguese — smooth, romantic, melodically sophisticated. Kizomba has become a major global partner dance style with classes worldwide. Fundamentally about physical and emotional intimacy.`,
    hitFormula: 'INTIMACY IS THE PRODUCT. The groove should feel like swaying together. The bass is felt in the body, not just heard. Romantic Portuguese lyrics about connection and closeness. Warm and enveloping production — space for two.',
    lyricTemplate: 'verse-hook',
  },
  {
    key: 'afrobeats_latin',
    name: 'Afro-Reggaeton',
    region: 'latin',
    emoji: '🌎',
    tagline: 'Nigeria meets Latin America',
    bpm: [95, 110],
    defaultLanguage: 'English + Spanish + Yoruba or Pidgin',
    styleTags: ['afrobeats', 'reggaeton', 'afro latin fusion', 'dembow rhythm', 'syncopated afrobeats shaker', '808 bass', 'pan-african latin', 'summer anthem'],
    referenceArtists: ['Wizkid + J. Balvin collabs', 'Afro B', 'Rema', 'Ozuna x Afrobeats collabs'],
    culturalDNA: `Afro-Reggaeton fuses West African Afrobeats with Latin Reggaeton — two of the most globally dominant music forms of the 2020s. The dembow (reggaeton's signature skipping kick-snare) locks with Afrobeats' syncopated hi-hat groove to create a polyrhythmic foundation neither genre has alone. Sub-bass borrows from both traditions. Vocals switch between English, Spanish, and Yoruba or Pidgin — representing the African diaspora through the Americas back to Africa. The fusion works because both genres share African diaspora rhythmic DNA: they are already cousins across the Atlantic.`,
    hitFormula: 'DEMBOW MEETS THE AFROBEATS SHAKER. Both rhythms must be present and interlocking. Code-switch between English, Spanish, and one Yoruba/Pidgin phrase per verse. Summer energy — outdoor festival music. The hook must work equally in Lagos and Medellín.',
    lyricTemplate: 'verse-hook',
  },
  {
    key: 'afrobeat_brasileiro',
    name: 'Afro-Brasileiro',
    region: 'latin',
    emoji: '🇧🇷',
    tagline: 'Bahia meets Lagos soul',
    bpm: [100, 115],
    defaultLanguage: 'Portuguese + Yoruba Orixá phrases',
    styleTags: ['afrobeat', 'brazilian music', 'samba influenced', 'afro brazilian', 'candomble rhythm', 'brass', 'percussion ensemble', 'spiritual groove'],
    referenceArtists: ['Gilberto Gil', 'Carlinhos Brown', 'Timbalada', 'Margareth Menezes'],
    culturalDNA: `Afro-Brasileiro is the Brazilian expression of African music consciousness — fusing Fela Kuti-inspired Afrobeat with Brazilian samba, Candomblé rhythms, and Bahian percussion culture. Bahia (Salvador) is the heart of this: where the African diaspora's music never stopped being African. Carlinhos Brown's Timbalada collective: hundreds of drummers performing Candomblé-derived rhythms at festival energy. Brass arrangements are celebratory and jazz-influenced. Portuguese lyrics reference African spiritual traditions (Orixás — Yoruba deities) — connecting Bahia to Yorubaland as one continuous culture.`,
    hitFormula: 'THE PERCUSSION ENSEMBLE IS THE SONG. Multiple drums must sound like a single rhythmic organism. Brass adds jubilation. Reference the Orixás, the sea, Bahia and Africa as one continuous people. Celebratory and spiritual simultaneously.',
    lyricTemplate: 'verse-hook',
  },
  {
    key: 'kizomba_zouk',
    name: 'Zouk / Cape Verde',
    region: 'latin',
    emoji: '🇨🇻',
    tagline: 'Cape Verdean ocean longing',
    bpm: [75, 95],
    defaultLanguage: 'Kriolu (Cape Verdean Creole) + Portuguese',
    styleTags: ['zouk', 'cape verdean music', 'morna influenced', 'slow romantic', 'atlantic soul', 'warm acoustic guitar', 'portuguese creole vocals', 'saudade'],
    referenceArtists: ['Cesária Évora', 'Mayra Andrade', 'Lura'],
    culturalDNA: `Cape Verdean music sits at the crossroads of Africa, Portugal, and the Caribbean — a small island nation whose music carries the emotional weight of oceanic distances and migration. Morna (Cesária Évora's music of saudade) is the predecessor. Zouk is the more danceable form — warm, sensual, slow. The Atlantic Ocean is in the music — slow rhythms feel like waves. Kriolu lyrics carry both African and Portuguese emotional traditions. It's music about being between places and people.`,
    hitFormula: 'SAUDADE (LONGING) IS THE PRODUCT. The track should feel like missing someone across an ocean. Warm acoustic guitar or light production. Kriolu lyrics should feel poetic and deeply felt. Slow rolling rhythm like ocean waves. Intimate, beautiful, bittersweet.',
    lyricTemplate: 'verse-hook',
  },
];

export const THEME_POOL = [
  { label: 'Fire',       value: 'fire, night, heat, movement, desire' },
  { label: 'Rain',       value: 'rain, water, rivers, cleansing, renewal' },
  { label: 'Ancestors',  value: 'ancestors, memory, roots, soil, spirits' },
  { label: 'City',       value: 'city lights, longing, distance, hustle, dreams' },
  { label: 'Love',       value: 'love, touch, warmth, presence, devotion' },
  { label: 'Dawn',       value: 'dawn, hope, new beginnings, light, tomorrow' },
  { label: 'Loss',       value: 'loss, grief, acceptance, healing, absence' },
  { label: 'Joy',        value: 'celebration, joy, freedom, dance, euphoria' },
  { label: 'Stillness',  value: 'silence, meditation, breath, stillness, peace' },
  { label: 'Resilience', value: 'strength, resilience, survival, pride, victory' },
];

export const LANGUAGE_OPTIONS: Record<RegionKey, string[]> = {
  north:  ['Darija Arabic', 'Modern Standard Arabic', 'French-Arabic mix', 'English + Arabic'],
  west:   ['English + Yoruba', 'English Only', 'Pidgin English', 'Yoruba Only', 'English + Twi', 'French + Wolof'],
  east:   ['Swahili', 'Swahili + English', 'English Only'],
  central:['Lingala', 'French + Lingala', 'English + Lingala'],
  south:  ['English + Zulu', 'English Only', 'Zulu / Sotho', 'English + Tswana'],
  latin:  ['Portuguese', 'English + Spanish + Yoruba', 'English + Spanish', 'Kriolu (Cape Verdean)', 'English + Yoruba'],
};

export const FUSION_PAIRS: Array<{ a: string; b: string; score: number; note: string }> = [
  { a: 'afro_house',      b: 'gnawa',           score: 5, note: 'Guembri under Afro House — proven global crossover' },
  { a: 'afrobeats',       b: 'highlife',         score: 5, note: 'Historical lineage — Afrobeats evolved from Highlife' },
  { a: 'amapiano',        b: 'bongo_flava',      score: 5, note: 'Bongopiano — established East/South crossover' },
  { a: 'taarab',          b: 'bongo_flava',      score: 4, note: 'Zuchu\'s template — taarab strings over Bongo Flava' },
  { a: 'soukous',         b: 'afro_house',       score: 4, note: 'Soukous guitar improv over Afro House groove' },
  { a: 'nubian',          b: 'afro_house',       score: 4, note: 'Nubian pentatonic is haunting inside house production' },
  { a: 'afrobeats',       b: 'afrobeats_latin',  score: 4, note: 'Lagos meets Latin — shared diaspora rhythms' },
  { a: 'kizomba',         b: 'afro_house',       score: 3, note: 'Angolan warmth meets South African depth' },
  { a: 'rai',             b: 'afrobeats',        score: 3, note: 'North meets West — Arabic vocals over Lagos rhythm' },
  { a: 'gnawa',           b: 'amapiano',         score: 3, note: 'Guembri bass meets log drum — trance meets groove' },
  { a: 'afro_drill',      b: 'afro_house',       score: 4, note: 'Street energy over Afro House groove — Burna Boy meets Black Coffee' },
  { a: 'tribal_house',    b: 'organic_house',    score: 5, note: 'Percussion ceremony meets acoustic warmth — perfect ritual house' },
  { a: 'afropiano',       b: 'afrobeats',        score: 5, note: 'Log drum meets Lagos hook — the Pan-African hit formula' },
  { a: 'afropiano',       b: 'bongo_flava',      score: 4, note: 'East meets South — Bongopiano extended to Tanzanian soul' },
  { a: 'organic_house',   b: 'gnawa',            score: 4, note: 'Guembri acoustic texture inside Organic House — haunting' },
  { a: 'tribal_house',    b: 'afro_house',       score: 4, note: 'Percussion ceremony with Afro House electronics — Enoo Napa style' },
];

export function getGenresByRegion(region: RegionKey): Genre[] {
  return GENRES.filter(g => g.region === region);
}

export function getGenreByKey(key: string): Genre | undefined {
  return GENRES.find(g => g.key === key);
}

export function getFusionScore(a: string, b: string): { score: number; note: string } | null {
  return FUSION_PAIRS.find(p => (p.a === a && p.b === b) || (p.a === b && p.b === a)) ?? null;
}

export interface ChannelProfile {
  id: string;
  name: string;
  emoji: string;
  defaultRegion: RegionKey;
  defaultGenreKey: string;
  defaultLanguage: string;
  description: string;
}

export const DEFAULT_CHANNELS: ChannelProfile[] = [
  {
    id: 'rooftop',
    name: 'Rooftop Sessions',
    emoji: '🌆',
    defaultRegion: 'south',
    defaultGenreKey: 'afro_house',
    defaultLanguage: 'English + Zulu',
    description: 'Deep Afro House — Black Coffee energy, late night boutique club',
  },
  {
    id: 'street',
    name: 'Street Tape Africa',
    emoji: '🏙️',
    defaultRegion: 'west',
    defaultGenreKey: 'afro_drill',
    defaultLanguage: 'English + Yoruba/Pidgin street mix',
    description: 'Afro Drill & Urban Afrobeats — Lagos street energy, mixed voices',
  },
  {
    id: 'global',
    name: 'Global Vibes',
    emoji: '🌍',
    defaultRegion: 'west',
    defaultGenreKey: 'afropop',
    defaultLanguage: 'English Only',
    description: 'Pan-African crossover — streaming-optimised, global audience',
  },
];
